# Generated by Django 5.1.7 on 2025-03-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prime',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
